# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Decentralized Cloud Standard
description: >- # this means to ignore newlines until "baseurl:"
  Decentralized Cloud Standards (DCSs) describe standards for the Akash platform, 
  including core protocol specifications, client APIs, and SDL standards.
url: "https://dcs.akash.network" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: akashnet_
github_username:  ovrclk

header_pages:
 - all.html
 - core.html
 - interface.html
 - economics.html
 - meta.html
 - informational.html
twitter:
  card: summary
  username: akashnet_

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: false
  # This is the default, but be explicit as some EIPs depend on it
  auto_ids: true
  # This is to ensure more determistic behaviour
  auto_id_stripping: true

theme: minima

defaults:
  -
    scope:
      path: "spec/*/README.md"
    values:
      layout: "dcs"
      permalink: ":path"

github:
  repository_url: https://github.com/ovrclk/dcs


collections:
  dcs:
    output: true
    path: "spec/*/README.md"
    permalink: /:collection/:dcs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dcs-template.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  - README.md
